slam_toolbox:
  ros__parameters:
    use_sim_time: true

    # Solver Plugin
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT

    # Frames
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan

    # Update Thresholds (Forces updates even during low-speed foot slip)
    mode: mapping
    map_update_interval: 0.5
    minimum_time_interval: 0.2
    minimum_travel_distance: 0.0
    minimum_travel_heading: 0.0

    # Scan Matcher Bounds
    resolution: 0.05
    max_laser_range: 25.0
    minimum_laser_range: 0.25
    use_scan_matching: true
    use_scan_barycenter: true
    distance_penalty_factor: 0.5
    angle_penalty_factor: 0.5

    # Graph Constraints
    transform_timeout: 0.5
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    enable_interactive_mode: false
